version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cookiecutter-apollo-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1loxbr6mioai7"
s3_prefix = "cookiecutter-apollo-server"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
